import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import QueryProvider from "@/providers/query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { TouchProvider } from "@/components/ui/hybrid-tooltip";
import ProgressProvider from "@/providers/progress-provider";
import { Toaster } from "@/components/ui/toast";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // See https://ui.shadcn.com/docs/dark-mode/next#wrap-your-root-layout for why we need to use `suppressHydrationWarning` here
        <html
            lang="en"
            className={cn("font-sans", figtree.variable)}
            suppressHydrationWarning
        >
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem
                    disableTransitionOnChange
                >
                    <QueryProvider>
                        <ProgressProvider>
                            <TouchProvider>{children}</TouchProvider>
                        </ProgressProvider>
                    </QueryProvider>
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
}
